// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddVoteParams is parameters of AddVote operation.
type AddVoteParams struct {
	PollId int64
}

func unpackAddVoteParams(packed middleware.Parameters) (params AddVoteParams) {
	{
		key := middleware.ParameterKey{
			Name: "pollId",
			In:   "path",
		}
		params.PollId = packed[key].(int64)
	}
	return params
}

func decodeAddVoteParams(args [1]string, argsEscaped bool, r *http.Request) (params AddVoteParams, _ error) {
	// Decode path: pollId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "pollId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.PollId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pollId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPollParams is parameters of getPoll operation.
type GetPollParams struct {
	PollId int64
}

func unpackGetPollParams(packed middleware.Parameters) (params GetPollParams) {
	{
		key := middleware.ParameterKey{
			Name: "pollId",
			In:   "path",
		}
		params.PollId = packed[key].(int64)
	}
	return params
}

func decodeGetPollParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPollParams, _ error) {
	// Decode path: pollId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "pollId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.PollId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pollId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetVoteParams is parameters of getVote operation.
type GetVoteParams struct {
	PollId int64
	VoteId int64
}

func unpackGetVoteParams(packed middleware.Parameters) (params GetVoteParams) {
	{
		key := middleware.ParameterKey{
			Name: "pollId",
			In:   "path",
		}
		params.PollId = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "voteId",
			In:   "path",
		}
		params.VoteId = packed[key].(int64)
	}
	return params
}

func decodeGetVoteParams(args [2]string, argsEscaped bool, r *http.Request) (params GetVoteParams, _ error) {
	// Decode path: pollId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "pollId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.PollId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pollId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: voteId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "voteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.VoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "voteId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
