// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddVoteId implements AddVoteId operation.
	//
	// Add a vote to a poll.
	//
	// POST /polls/{pollId}/vote
	AddVoteId(ctx context.Context, req VoteCreationParameter, params AddVoteIdParams) (AddVoteIdRes, error)
	// CreatePollId implements CreatePollId operation.
	//
	// Create a new poll.
	//
	// POST /polls/create
	CreatePollId(ctx context.Context, req *PollCreationParameter) (CreatePollIdRes, error)
	// GetPollId implements getPollId operation.
	//
	// Get a specific poll.
	//
	// GET /polls/{pollId}
	GetPollId(ctx context.Context, params GetPollIdParams) (GetPollIdRes, error)
	// GetVoteId implements getVoteId operation.
	//
	// Get a specific vote in a poll.
	//
	// GET /polls/{pollId}/vote/{voteId}
	GetVoteId(ctx context.Context, params GetVoteIdParams) (GetVoteIdRes, error)
	// LoginId implements loginId operation.
	//
	// User login.
	//
	// POST /auth/login
	LoginId(ctx context.Context, req *LoginParameter) (LoginIdRes, error)
	// RegisterId implements RegisterId operation.
	//
	// Register a new user.
	//
	// POST /auth/register
	RegisterId(ctx context.Context, req *UserRegisterParameter) (RegisterIdRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
