// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddVoteIdParams is parameters of AddVoteId operation.
type AddVoteIdParams struct {
	PollId string
}

func unpackAddVoteIdParams(packed middleware.Parameters) (params AddVoteIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "pollId",
			In:   "path",
		}
		params.PollId = packed[key].(string)
	}
	return params
}

func decodeAddVoteIdParams(args [1]string, argsEscaped bool, r *http.Request) (params AddVoteIdParams, _ error) {
	// Decode path: pollId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "pollId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.PollId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pollId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPollIdParams is parameters of getPollId operation.
type GetPollIdParams struct {
	PollId int
}

func unpackGetPollIdParams(packed middleware.Parameters) (params GetPollIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "pollId",
			In:   "path",
		}
		params.PollId = packed[key].(int)
	}
	return params
}

func decodeGetPollIdParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPollIdParams, _ error) {
	// Decode path: pollId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "pollId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.PollId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pollId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetVoteIdParams is parameters of getVoteId operation.
type GetVoteIdParams struct {
	PollId string
	VoteId string
}

func unpackGetVoteIdParams(packed middleware.Parameters) (params GetVoteIdParams) {
	{
		key := middleware.ParameterKey{
			Name: "pollId",
			In:   "path",
		}
		params.PollId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "voteId",
			In:   "path",
		}
		params.VoteId = packed[key].(string)
	}
	return params
}

func decodeGetVoteIdParams(args [2]string, argsEscaped bool, r *http.Request) (params GetVoteIdParams, _ error) {
	// Decode path: pollId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "pollId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.PollId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "pollId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: voteId.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "voteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.VoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "voteId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
