// Code generated by ogen, DO NOT EDIT.
package api

type AddVoteRes interface {
	addVoteRes()
}

type CreatePollRes interface {
	createPollRes()
}

type GetPollRes interface {
	getPollRes()
}

type GetVoteRes interface {
	getVoteRes()
}

type LoginRes interface {
	loginRes()
}

type RegisterRes interface {
	registerRes()
}
