// Code generated by ogen, DO NOT EDIT.
package api

type AddVoteIdRes interface {
	addVoteIdRes()
}

type CreatePollIdRes interface {
	createPollIdRes()
}

type GetPollIdRes interface {
	getPollIdRes()
}

type GetVoteIdRes interface {
	getVoteIdRes()
}

type LoginIdRes interface {
	loginIdRes()
}

type RegisterIdRes interface {
	registerIdRes()
}
