// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddVoteId implements AddVoteId operation.
//
// Add a vote to a poll.
//
// POST /polls/{pollId}/vote
func (UnimplementedHandler) AddVoteId(ctx context.Context, req VoteCreationParameter, params AddVoteIdParams) (r AddVoteIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePollId implements CreatePollId operation.
//
// Create a new poll.
//
// POST /polls/create
func (UnimplementedHandler) CreatePollId(ctx context.Context, req *PollCreationParameter) (r CreatePollIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPollId implements getPollId operation.
//
// Get a specific poll.
//
// GET /polls/{pollId}
func (UnimplementedHandler) GetPollId(ctx context.Context, params GetPollIdParams) (r GetPollIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVoteId implements getVoteId operation.
//
// Get a specific vote in a poll.
//
// GET /polls/{pollId}/vote/{voteId}
func (UnimplementedHandler) GetVoteId(ctx context.Context, params GetVoteIdParams) (r GetVoteIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginId implements loginId operation.
//
// User login.
//
// POST /auth/login
func (UnimplementedHandler) LoginId(ctx context.Context, req *LoginParameter) (r LoginIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterId implements RegisterId operation.
//
// Register a new user.
//
// POST /auth/register
func (UnimplementedHandler) RegisterId(ctx context.Context, req *UserRegisterParameter) (r RegisterIdRes, _ error) {
	return r, ht.ErrNotImplemented
}
