// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/jx"
)

// AddVoteOK is response for AddVote operation.
type AddVoteOK struct{}

func (*AddVoteOK) addVoteRes() {}

type BadRequest struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *BadRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *BadRequest) SetMessage(val string) {
	s.Message = val
}

func (*BadRequest) addVoteRes()  {}
func (*BadRequest) loginRes()    {}
func (*BadRequest) registerRes() {}

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

type InternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

// InternalServerErrorStatusCode wraps InternalServerError with StatusCode.
type InternalServerErrorStatusCode struct {
	StatusCode int
	Response   InternalServerError
}

// GetStatusCode returns the value of StatusCode.
func (s *InternalServerErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *InternalServerErrorStatusCode) GetResponse() InternalServerError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *InternalServerErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *InternalServerErrorStatusCode) SetResponse(val InternalServerError) {
	s.Response = val
}

func (*InternalServerErrorStatusCode) addVoteRes()    {}
func (*InternalServerErrorStatusCode) createPollRes() {}
func (*InternalServerErrorStatusCode) getPollRes()    {}
func (*InternalServerErrorStatusCode) loginRes()      {}
func (*InternalServerErrorStatusCode) registerRes()   {}

type LoginOKApplicationJSON jx.Raw

func (*LoginOKApplicationJSON) loginRes() {}

// Ref: #/components/schemas/LoginParameter
type LoginParameter struct {
	UserId   string `json:"userId"`
	Password string `json:"password"`
}

// GetUserId returns the value of UserId.
func (s *LoginParameter) GetUserId() string {
	return s.UserId
}

// GetPassword returns the value of Password.
func (s *LoginParameter) GetPassword() string {
	return s.Password
}

// SetUserId sets the value of UserId.
func (s *LoginParameter) SetUserId(val string) {
	s.UserId = val
}

// SetPassword sets the value of Password.
func (s *LoginParameter) SetPassword(val string) {
	s.Password = val
}

type NotFound struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *NotFound) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *NotFound) SetMessage(val string) {
	s.Message = val
}

func (*NotFound) addVoteRes() {}
func (*NotFound) getPollRes() {}
func (*NotFound) getVoteRes() {}

type PingOK struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingOK) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingOK) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/PollCreationParameter
type PollCreationParameter struct {
	Title         string   `json:"title"`
	Description   string   `json:"description"`
	CreatorUserId string   `json:"creatorUserId"`
	Options       []string `json:"options"`
}

// GetTitle returns the value of Title.
func (s *PollCreationParameter) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *PollCreationParameter) GetDescription() string {
	return s.Description
}

// GetCreatorUserId returns the value of CreatorUserId.
func (s *PollCreationParameter) GetCreatorUserId() string {
	return s.CreatorUserId
}

// GetOptions returns the value of Options.
func (s *PollCreationParameter) GetOptions() []string {
	return s.Options
}

// SetTitle sets the value of Title.
func (s *PollCreationParameter) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *PollCreationParameter) SetDescription(val string) {
	s.Description = val
}

// SetCreatorUserId sets the value of CreatorUserId.
func (s *PollCreationParameter) SetCreatorUserId(val string) {
	s.CreatorUserId = val
}

// SetOptions sets the value of Options.
func (s *PollCreationParameter) SetOptions(val []string) {
	s.Options = val
}

type PollInfo jx.Raw

func (*PollInfo) createPollRes() {}
func (*PollInfo) getPollRes()    {}

type RegisterCreatedApplicationJSON jx.Raw

func (*RegisterCreatedApplicationJSON) registerRes() {}

// Ref: #/components/schemas/UserRegisterParameter
type UserRegisterParameter struct {
	UserId   string `json:"userId"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// GetUserId returns the value of UserId.
func (s *UserRegisterParameter) GetUserId() string {
	return s.UserId
}

// GetName returns the value of Name.
func (s *UserRegisterParameter) GetName() string {
	return s.Name
}

// GetPassword returns the value of Password.
func (s *UserRegisterParameter) GetPassword() string {
	return s.Password
}

// SetUserId sets the value of UserId.
func (s *UserRegisterParameter) SetUserId(val string) {
	s.UserId = val
}

// SetName sets the value of Name.
func (s *UserRegisterParameter) SetName(val string) {
	s.Name = val
}

// SetPassword sets the value of Password.
func (s *UserRegisterParameter) SetPassword(val string) {
	s.Password = val
}

type VoteCreationParameter jx.Raw

type VoteInfo jx.Raw

func (*VoteInfo) getVoteRes() {}
